sampler2D texture : register(s0);

float4x4 worldMat : register(c0);

struct VS_IN {
	float3 posL 	: POSITION;
	float2 tex0 	: TEXCOORD0;
};

struct VS_OUT {
	float4 posH 	: SV_POSITION;
	float2 tex0 	: TEXCOORD2;
};

struct PS_OUT {
	float4 color: COLOR0;
};

VS_OUT VS_MAIN(VS_IN In, uint VertexID : VERTEXID) {
	VS_OUT vout;
	vout.tex0 = In.tex0;
	vout.posH = mul(In.posL,worldMat);
	return vout;
}

PS_OUT PS_MAIN(VS_OUT In) {
	PS_OUT Out;
		Out.color = tex2DtextureIn.tex0);
	return Out;
};