////////////////////////////////////////////////////////////////////////////////
//	Lighting shader for SPOT lights
//
////////////////////////////////////////////////////////////////////////////////

#include "deferred_lightpass_cmn.cginc"


//------------------------------------------------------------------------------
//	Vertex shader
//------------------------------------------------------------------------------

struct VS_IN {
	float3 posL 	: POSITION;
	float2 tex0 	: TEXCOORD0;
};
struct VS_OUT {
	float4 posH 	: SV_POSITION;
	float2 tex0 	: TEXCOORD2;
};

VS_OUT VS_MAIN(VS_IN In) {
	
}

//------------------------------------------------------------------------------
//	Helper functions
//------------------------------------------------------------------------------


float LightAttenuation() {
	return 1.f;
}


//------------------------------------------------------------------------------
//	Pixel shader
//------------------------------------------------------------------------------
float4 PS_MAIN(VS_OUT In) : COLOR0 {
	float4 color;
	float3 normal;
	float3 worldPos;
	float3 diffuseColor;
	float depth;
	DecodeGBuffer(In.tex0, diffuseColor, normal, worldPos, depth);
	
	// calculate lighting terms
	float3 diffuseTerm = DiffuseLight(lightDir, lightColor, normal);
	float3 specTerm = SpecularLight(lightDir, lightColor, normal, normalize(worldPos-camPos), 0.2f);

	color.rgb += diffuseTerm*diffuseColor + specTerm; // note: no light attenuation
	color.rgb *= LightAttenuation();

	color.a = 1.f;
	
	return color;
}